### ISSUE TITLE
[Question] How do I use this field?

### ISSUE THREAD

**Issue by mooror** [svandragt/silverstripe-ajaxuniquetextfield#4]
I have on many occasions tried to use this field, but every time I do it doesn't work for one reason or another. I have done searches and even inquired about this in the IRC with no progress. 
Perhaps its due to me using silverstripe 3.4 instead of 3., but if its not I wish to know what I'm doing wrong. Heres my code
```
AjaxUniqueTextField::create('Name',null,'Name','Object'),
``` 

Thanks in advance,
Mooror

**Comment by svandragt** [comment]
Hi Mooror,
I've extracted a general example from my legacy codebase where I was using this for you and added it to the README.md file also:

Have a look at:
https://gist.github.com/svandragt/e937ae033b78d35117f908abd6711273

In this example I want the user to type a string as MyCode but it can't have been used by other records.
